### ISSUE TITLE
A message concerning your Catalyst fork

### ISSUE THREAD

**Issue by jdev082** [redstone-scratch/Redstone-scratch#1]
👋 Hello, @redstone-scratch 👋 

This is a message concerning your Catalyst fork *Platinum*, I request that you enable GitHub issues on your fork and complete rebranding ASAP.

**Comment by redstone-dev** [comment]
Why? It's (mostly) fully rebranded.

Granted, it _is_ just Ctrl+F on the entire source code, but...
