### ISSUE TITLE
you leaked your email :skull: 

### ISSUE THREAD

**Issue by errplanedev** [redstone-scratch/Redstone-scratch#2]
you didn't respond to my email (address starts with wjvs), so imma tell you here.
just email me for how to remove it (or respond to this issue)

**Comment by redstone-dev** [comment]
how did i leak it? please tell me how to remove it

**Comment by errplanedev** [comment]
i found it in your is-a.dev fork

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by redstone-dev** [comment]
thanks, i deleted it 👍🏻
